### ISSUE TITLE
Usage of std::net::IpAddr is unstable

### ISSUE THREAD

**Issue by faern** [achanda/ipnetwork#1]
When reverting using the `ip` crate and using `std::net::IpAddr` instead this crate does not build on stable rust.

**Comment by achanda** [comment]
I have been building and testing against nightly. I do agree that using the `ip` crate will make it more usable across all releases of rust. I will go ahead and revert the revert. Thanks.

**Comment by achanda** [comment]
Updated and published v0.6.0. Closing the issue now.

**Comment by oblique** [comment]
`std::net::IpAddr` is now stable in rust 1.7.0. The developer of `ip` is suggesting `std::net::IpAddr`[1].

[1] https://github.com/dimbleby/ip-rs

**Comment by achanda** [comment]
Updated and published. Thanks @oblique
