### ISSUE TITLE
Parsing from ip/mask string

### ISSUE THREAD

**Issue by vorner** [achanda/ipnetwork#107]
Currently the Ipv4Network can be parsed from `ip/prefix` representation (eg. `192.168.2.1/24`), but the older `ip/mask` (`192.168.2.1/255.255.255.0`) is rejected. Would it make sense to add such support too?

**Comment by achanda** [comment]
Sure, sounds good. The only reason it was not added is no one requested it :)

**Comment by vorner** [comment]
OK, I'll put it into my queue to send it it. It might happen in a week or two, hopefully.

**Comment by achanda** [comment]
Thanks @vorner!
