### ISSUE TITLE
Relicense to a dual license?

### ISSUE THREAD

**Issue by CameronNemo** [achanda/ipnetwork#127]
The Apache 2.0 license is more complicated than it needs to be, and the patent clause can get in the way in some scenarios. I would like to respectfully ask that the author, @achanda, and other contributors (primarily @faern) agree to add a second license that does not mention patents (BSD-2-Clause, MIT, BSD-3-Clause, 0BSD, are all great options). This is common in Rust projects that I have seen (including the language implementation itself).

**Comment by faern** [comment]
`MIT OR Apache-2.0` is basically the de facto standard license for most crates on crates.io. I don't have anything against adopting said dual license in this crate.

**Comment by achanda** [comment]
Thanks for bringing this up. I have opened a PR.
