### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by paolobarbolini** [achanda/ipnetwork#147]
Hello, seeing that 9651b3b72196376e4df0c435ce62a4b559578df7 bumped the edition to 2021 I imagine the next release will have to be 0.19.0. Since I use this crate through sqlx, which does a low number of minor version bumps, maybe it could make sense to release ipnetwork 0.19.0 **now** so that we could get it in sqlx 0.6 (coming out in a few days) https://github.com/launchbadge/sqlx/issues/1793#issuecomment-1097053734 ?

Otherwise it'll most likely take about a year before sqlx releases 0.7, allowing for another chance to bump the `ipnetwork` version again

**Comment by achanda** [comment]
I have released v0.19.0 on crates.io. Hoping to get the release workflow automated soon. Thanks for flagging this @paolobarbolini

**Comment by paolobarbolini** [comment]
Thank you very much for the quick response. I've bumped ipnetwork in sqlx
