### ISSUE TITLE
JSONSchema implementation

### ISSUE THREAD

**Issue by cab404** [achanda/ipnetwork#153]
Hi there!
I was trying to make a json schema for [wg-bond](https://github.com/cab404/wg-bond/issues) (via [schemars](https://docs.rs/schemars/latest/schemars/)), and got stuck on missing implementation for IpNetwork. Can I add implementation of JsonSchema for your stuff in your crate?

**Comment by achanda** [comment]
HI, @cab404 please feel free to add a JsonSchema implementation. Thank you!
