### ISSUE TITLE
Question about constructing IpNetWork

### ISSUE THREAD

**Issue by samrayleung** [achanda/ipnetwork#59]
I have checked [IpNetwork api doc](https://docs.rs/ipnetwork/0.12.2/ipnetwork/enum.IpNetwork.html), and I could not find a way to construct `IpNewWork` from `IpAddr` which is defined in Rust standard library. It seems I have to specify a `prefix` field when I construct `IpNewWork`. Is there other way to construct `IpNewWork` from `IpAddr` ?

**Comment by achanda** [comment]
This feature was recently added and release, the version you are looking at is a bit old. Version 0.12.7 has a `From<IpAddr>` implementation for `IpNetwork` and is documented here https://docs.rs/ipnetwork/0.12.7/ipnetwork/enum.IpNetwork.html#impl-From<IpAddr>

Do let me know if this helps!

**Comment by samrayleung** [comment]
It does help me a lot. Thanks so much for your help :)
