### ISSUE TITLE
Serde support doesn't work as expected

### ISSUE THREAD

**Issue by rushmorem** [achanda/ipnetwork#73]
For example, if you get a JSON payload with network addresses like "10.0.0.0/24" or "fd00::/64" it won't be deserialised to `IpNetwork`. A quick look at the code confirms this. `derive(Serialize, Deserialize)` doesn't cut it here. Those traits will need to be implemented manually.

**Comment by achanda** [comment]
@rushmorem thanks for the report. Those values you cited are strings, not json. You need to call `.parse()` on those to convert those to `IpNetwork`. This example works fine for me.

```
extern crate ipnetwork;

use ipnetwork::IpNetwork;

fn main() {
    let foo: IpNetwork = "10.0.0.0/24".parse().unwrap();
    let bar: IpNetwork = "fd00::/64".parse().unwrap();

    println!("{}", foo.prefix());
    println!("{}", bar.prefix());
}
```

**Comment by sharksforarms** [comment]
@rushmorem is right, if we want it to deserialize from a single string and not an object

See this PR for test cases/examples on how it's currently serialized/deserialized
https://github.com/achanda/ipnetwork/pull/74

**Comment by rushmorem** [comment]
@achanda 

> Those values you cited are strings, not json.

I know. But, like I said, if a JSON payload contains those strings, they won't be deserialised correctly as network addresses.

> You need to call `.parse()` on those to convert those to `IpNetwork`.

Not if I'm using `serde` to deserialise for me. I expect this library's `Deserialize` implementation to do that for me.

> This example works fine for me.

Your example is testing your parser, not your implementation for `serde`. It doesn't involve `serde` in any way.

@sharksforarms 

> See this PR for test cases/examples on how it's currently serialized/deserialized

Exactly. This is how the default derive implementation of `serde`, which is what this library does, works. This is why I said [manual implementation](https://github.com/krisprice/ipnet/pull/6/files#diff-df0f2af5263ebcf45661002d6f38ab40) of `serde`'s traits is needed. The current implementation doesn't add much value as far as `serde` support goes. In one of your examples you have:

```rust
let json_string = r#"{"ipnetwork":{"addr":"127.1.0.0","prefix":24}}"#;
```
This can easily be represented as follows, without relying on this library at all:

```rust
#[derive(Serialize, Deserialize)]
struct CustomIpv4Network {
    addr: Ipv4Addr,
    prefix: u8,
}

#[derive(Serialize, Deserialize)]
struct MyStruct {
    ipnetwork: CustomIpv4Network,
}
```

In any case, that is not how network addresses are commonly represented. CIDR notation, as most (if not all) of your examples show, is typically used. Here is a test case that fails with the current implementation:

```rust
extern crate ipnetwork;
extern crate serde;
#[macro_use]
extern crate serde_derive;
extern crate serde_json;

use ipnetwork::Ipv4Network;

#[derive(Serialize, Deserialize)]
struct MyStruct {
    network: Ipv4Network,
}

fn main() {
    let json_string = r#"{"network": "10.1.9.32/16"}"#;

    let mystruct: MyStruct = serde_json::from_str(json_string).unwrap();

    assert_eq!(mystruct.network.prefix(), 16);
}
```

```text
~> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/net`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: string \"10.1.9.32/16\", expected struct Ipv4Network", line: 1, column: 26)', libcore/result.rs:945:5
```

IMHO, this is the case that this library should support.

**Comment by sharksforarms** [comment]
I agree. The library should implement its own serialize/deserialize trait. I'll add this to the PR

**Comment by achanda** [comment]
Sorry, I misunderstood. Agreed that this is a common use case and should be supported.

**Comment by rushmorem** [comment]
> Sorry, I misunderstood.

It's OK. I should have been more explicit in my original comment.

**Comment by sharksforarms** [comment]
Made changes in:
https://github.com/achanda/ipnetwork/pull/74
