### ISSUE TITLE
fn size() on Ipv4Network returns an u64?

### ISSUE THREAD

**Issue by stusmall** [achanda/ipnetwork#82]
https://docs.rs/ipnetwork/0.13.0/ipnetwork/struct.Ipv4Network.html#method.size

Is it safe to change this method to return a u32 since IPv4 networks can never be bigger than 32 bits? Would you mind if I sent a PR that introduces a breaking change to this API?  It would help me cut a cast out of my code.

**Comment by stusmall** [comment]
I'm just checking for overlap in Ipv4Network structs.  For a new value I calculate the first and last addresses with:

` 
let incoming_fist = incoming_cidr.network();
let incoming_last = Ipv4Addr::from(u32::from(incoming_fist) + (incoming_cidr.size() as u32));
`

and then check to see if either of those are contained in the other Ipv4Network.  Casts always make me suspicious so I like to minimize them where I can.  Even when it's safe it's one more thing to keep in mind.

**Comment by achanda** [comment]
@stusmall sorry it took me so long to get back to you on this. But I opened https://github.com/achanda/ipnetwork/pull/84 Please feel free to review.

**Comment by achanda** [comment]
Closing this for now since I merged the PR.
